<?php
/**
 * Seed the Home page with the full set of populated ACF blocks.
 *
 * Run from the Bedrock root:
 *   wp eval-file scripts/seed-homepage.php
 *
 * Idempotent: reuses the existing "Home" page (or the current front page)
 * and overwrites its content with the homepage block stack.
 */

if (! function_exists('acf_get_fields')) {
    fwrite(STDERR, "ACF is not active.\n");
    exit(1);
}

/**
 * Recursively flatten a name-keyed data array into ACF block "data" format,
 * resolving field keys from the registered field group definition.
 */
function esa_flatten_acf(array $fields, array $data, string $prefix, array &$out): void
{
    foreach ($fields as $field) {
        $name = $field['name'] ?? '';

        if ($name === '' || ! array_key_exists($name, $data)) {
            continue;
        }

        $key = $field['key'];
        $value = $data[$name];

        if ($field['type'] === 'group' && ! empty($field['sub_fields'])) {
            // ACF needs the group's own field reference in the meta store so
            // get_field('group') resolves; sub-fields are stored flattened.
            $out["{$prefix}{$name}"] = '';
            $out["_{$prefix}{$name}"] = $key;
            esa_flatten_acf($field['sub_fields'], (array) $value, "{$prefix}{$name}_", $out);
            continue;
        }

        if ($field['type'] === 'repeater' && ! empty($field['sub_fields'])) {
            $rows = (array) $value;
            $out["{$prefix}{$name}"] = count($rows);
            $out["_{$prefix}{$name}"] = $key;

            foreach (array_values($rows) as $i => $row) {
                esa_flatten_acf($field['sub_fields'], (array) $row, "{$prefix}{$name}_{$i}_", $out);
            }

            continue;
        }

        $out["{$prefix}{$name}"] = $value;
        $out["_{$prefix}{$name}"] = $key;
    }
}

/** Build an acf block comment for the given block name + field group. */
function esa_block(string $blockName, string $groupKey, array $data, array $extra = []): string
{
    $fields = acf_get_fields($groupKey);

    if (! $fields) {
        fwrite(STDERR, "Field group {$groupKey} not found; skipping {$blockName}.\n");

        return '';
    }

    $flat = [];
    esa_flatten_acf($fields, $data, '', $flat);

    $attributes = array_merge([
        'name' => $blockName,
        'data' => $flat,
        'align' => 'full',
        'mode' => 'preview',
    ], $extra);

    return '<!-- wp:' . $blockName . ' '
        . wp_json_encode($attributes, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
        . ' /-->';
}

/** Look up an imported attachment id by filename slug. */
function esa_attachment_id(string $like): int
{
    $q = new WP_Query([
        'post_type' => 'attachment',
        'post_status' => 'inherit',
        'posts_per_page' => 1,
        'fields' => 'ids',
        's' => $like,
    ]);

    return $q->posts[0] ?? 0;
}

/** Convert double-newline separated text into <p> paragraphs. */
function esa_paragraphs(string $text): string
{
    $parts = preg_split('/\n\n+/', trim($text)) ?: [];

    return implode('', array_map(
        static fn ($p) => '<p>' . trim($p) . '</p>',
        array_filter($parts, static fn ($p) => trim($p) !== '')
    ));
}

/* ---- Media -------------------------------------------------------------- */
$mPoster = esa_attachment_id('Closeup_Hero_LowRes_Poster');
$mWide = esa_attachment_id('ESA_Wide_Hero');
$mPortrait = esa_attachment_id('ESA_Portrait_Hero');
$mDay = esa_attachment_id('Day_at_ESA');
$mClassroom = esa_attachment_id('esa-classroom-academics');
$mPractice = esa_attachment_id('Practice_Hero1');
$mMap = esa_attachment_id('map');
$mTexture = esa_attachment_id('texture1');
$mOffice = esa_attachment_id('office_4');
$mGroup = esa_attachment_id('group');
$mCampFlyer = esa_attachment_id('ESA-FREE-Camp-Flyer');
$mParent = esa_attachment_id('Parent_Hero');
$mTeacher = esa_attachment_id('Teacher');

/* Brand icon PNGs (generated by scripts/generate-icons.php). */
$icon = [];
foreach (['liberty', 'integrity', 'leadership', 'college', 'scholarships', 'guidance', 'technique', 'strength', 'recovery', 'mental'] as $iconSlug) {
    $icon[$iconSlug] = esa_attachment_id($iconSlug);
}

/* ---- Shared CTAs -------------------------------------------------------- */
$applyUrl = 'https://heritageacademy.schoolmint.net/';
$tourUrl = 'https://docs.google.com/forms/d/e/1FAIpQLSdagnRNZfXdf5yl_XXAaBS2Cn_DgD7qNzdJElZUtp8ngKnxoA/viewform';

$blocks = [];

/* ---- Hero --------------------------------------------------------------- */
$blocks[] = esa_block('acf/hero', 'group_hero', [
    'eyebrow' => 'Elite Sports Academy',
    'headline' => 'Where Serious Athletes Are Built',
    'brand_line' => 'Building Scholars. Shaping Citizens. Training Champions.',
    'subhead' => '<p>A 6th-12th grade private academy combining rigorous academics, elite daily training, and character development to prepare students for success in sport, school, and life.</p>',
    'micro' => 'West Phoenix campus opening Fall 2026',
    'buttons' => [
        ['label' => 'Apply Now', 'url' => $applyUrl, 'new_tab' => true, 'variant' => 'primary'],
        ['label' => 'Schedule a Tour', 'url' => $tourUrl, 'new_tab' => true, 'variant' => 'secondary'],
    ],
    'card' => [
        'heading' => 'The Daily Standard',
        'support' => '<p>Half the day in rigorous academics. Half the day in elite training. Every day built with purpose.</p>',
        'stats' => [
            ['value' => '6th-12th Grade', 'label' => 'Private academy', 'link_label' => '', 'link_url' => ''],
            ['value' => '$15,500', 'label' => 'Annual tuition', 'link_label' => 'More Info', 'link_url' => '/tuition'],
            ['value' => '69K', 'label' => 'Square foot campus', 'link_label' => '', 'link_url' => ''],
        ],
    ],
    'media' => [
        'poster' => $mPoster,
        'video_landscape' => $mWide,
        'video_portrait' => $mPortrait,
        'sound_label' => 'Play Film',
        'sound_label_active' => 'Sound Off',
    ],
    'meta' => [
        'location_text' => 'SE corner of 43rd Ave and Peoria Rd, West Phoenix',
        'map_url' => 'https://www.google.com/maps/place/10215+N+43rd+Ave,+Phoenix,+AZ+85051',
        'phone_label' => '480-461-4487',
        'phone_url' => 'tel:4804614487',
    ],
    'padding_top' => 1,
    'padding_bottom' => 1,
]);

/* ---- Why ESA (model) ---------------------------------------------------- */
$blocks[] = esa_block('acf/why-esa', 'group_why_esa', [
    'eyebrow' => 'Why Elite?',
    'title' => 'Half-day academics. Half-day elite training. Full-day purpose.',
    'body' => esa_paragraphs('Elite splits the school day into two focused halves: rigorous academics and elite training, with recovery and character development built into the rhythm. Families get one integrated model instead of juggling school, coaching, tutoring, and late-night training across town.'),
    'payoff' => [
        ['text' => 'No second commute.', 'color' => 'orange'],
        ['text' => 'No after-hours scramble.', 'color' => 'purple'],
        ['text' => 'Just one school day built for athletes.', 'color' => 'white'],
    ],
    'image' => $mDay,
    'pillars' => [
        ['title' => 'Academics', 'copy' => esa_paragraphs("Focused classroom time built on Heritage Academy's proven curriculum in math, science, history, English, and enrichment.")],
        ['title' => 'Training', 'copy' => esa_paragraphs('Daily performance work centered on strength and conditioning, speed and agility, recovery, and sports psychology.')],
        ['title' => 'Recovery', 'copy' => esa_paragraphs('Recovery and wellness are part of the development model so athletes can train with more consistency and long-term support.')],
        ['title' => 'Growth', 'copy' => esa_paragraphs('Character, responsibility, leadership, and discipline stay connected to the student-athlete experience every day.')],
    ],
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Academics (Media + Text) ------------------------------------------ */
$blocks[] = esa_block('acf/media-text', 'group_media_text', [
    'eyebrow' => 'Academics That Achieve',
    'title' => 'Focused academics with real structure and momentum.',
    'body' => esa_paragraphs('Elite scholars follow the same Heritage Academy curriculum trusted by Arizona families for decades, with a focused academic environment built for progress and success.'),
    'bullets' => [
        ['text' => 'Core academics in math, science, history, and English'],
        ['text' => 'Dual enrollment opportunities for early college credit'],
        ['text' => 'A focused approach to academic excellence'],
    ],
    'buttons' => [
        ['label' => 'Learn more about academics', 'url' => '/academics', 'new_tab' => false, 'variant' => 'secondary'],
    ],
    'image' => $mClassroom,
    'image_side' => 'right',
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Training ----------------------------------------------------------- */
$blocks[] = esa_block('acf/training', 'group_training', [
    'eyebrow' => 'Elite Training',
    'title' => 'Perfect Practice Makes Perfect',
    'body' => esa_paragraphs("Practice does not make perfect. Perfect practice makes perfect habits permanent.\n\nAt Elite, every rep has a standard. Athletes are coached, corrected, and pushed to move with purpose until technique becomes instinct. Led by some of Arizona's top coaches, students build speed, strength, recovery habits, and discipline into the school day, not after it.\n\nWhen game-day pressure hits, they do not just compete. They dominate with precision."),
    'image' => $mPractice,
    'pillars' => [
        ['title' => 'Proper Technique', 'copy' => esa_paragraphs('Coach the right mechanics and habits so every rep counts.'), 'icon_image' => $icon['technique']],
        ['title' => 'Strength, Speed & Agility', 'copy' => esa_paragraphs('Build power, quickness, footwork, and athletic preparation.'), 'icon_image' => $icon['strength']],
        ['title' => 'Recovery & Wellness', 'copy' => esa_paragraphs('Develop recovery habits that support readiness and long-term health.'), 'icon_image' => $icon['recovery']],
        ['title' => 'Mental Performance', 'copy' => esa_paragraphs('Train focus, resilience, confidence, and composure under pressure.'), 'icon_image' => $icon['mental']],
    ],
    'sports' => [
        'label' => 'Sports Offered',
        'title' => 'Programs for boys and girls. Built for athletes who want more.',
        'image' => $mGroup,
        'intro' => 'Elite offers programs in:',
        'groups' => [
            ['label' => 'Boys & Girls', 'items' => [['name' => 'Basketball'], ['name' => 'Soccer'], ['name' => 'Volleyball']]],
            ['label' => 'Boys', 'items' => [['name' => 'Baseball'], ['name' => 'Football']]],
            ['label' => 'Girls', 'items' => [['name' => 'Softball'], ['name' => 'Flag Football']]],
        ],
    ],
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Campus ------------------------------------------------------------- */
$blocks[] = esa_block('acf/campus', 'group_campus', [
    'eyebrow' => 'Campus & Facilities',
    'title' => 'A campus designed for athletes and scholars.',
    'body' => esa_paragraphs("Elite's West Phoenix campus is built to support the full student-athlete experience, with academic, athletic, and performance spaces designed to work together."),
    'stats' => [
        ['value' => '69K', 'label' => 'Square foot campus'],
        ['value' => '4.5', 'label' => 'Acre site'],
        ['value' => '$15,500', 'label' => 'Tuition per year'],
    ],
    'map' => $mMap,
    'address' => [
        ['text' => 'Elite Sports Academy Campus'],
        ['text' => '10215 N. 43rd Ave, Phoenix, AZ 85051'],
    ],
    'features' => [
        ['text' => 'Gym and training spaces'],
        ['text' => 'Newly remodeled weight room'],
        ['text' => 'Two-story classroom buildings'],
        ['text' => 'Multipurpose and specialty rooms'],
        ['text' => 'Computer / TV production studio'],
        ['text' => 'Cafeteria'],
        ['text' => 'Performance stage / auditorium'],
        ['text' => 'Administrative and support spaces'],
    ],
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Character ---------------------------------------------------------- */
$blocks[] = esa_block('acf/character', 'group_character', [
    'eyebrow' => 'Character & Leadership',
    'title' => 'Talent gets attention. Character earns trust.',
    'body' => esa_paragraphs('Elite builds character into the daily rhythm of school and sport. Students are expected to lead with integrity, take responsibility for their choices, serve their teammates, and understand that freedom requires discipline.'),
    'intro' => 'Character is not a side program. It is built into the way students train, study, lead, and serve.',
    'image' => $mTexture,
    'framework' => [
        ['title' => 'Liberty', 'copy' => esa_paragraphs('Freedom requires self-government, discipline, and responsibility.'), 'icon' => 'shield', 'icon_image' => $icon['liberty']],
        ['title' => 'Integrity', 'copy' => esa_paragraphs('Do the right thing when the coach, teacher, or crowd is not watching.'), 'icon' => 'scales', 'icon_image' => $icon['integrity']],
        ['title' => 'Leadership', 'copy' => esa_paragraphs('Lead through service, respect, teamwork, and accountability.'), 'icon' => 'community', 'icon_image' => $icon['leadership']],
    ],
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- What Comes Next (future) ------------------------------------------ */
$blocks[] = esa_block('acf/what-comes-next', 'group_what_comes_next', [
    'eyebrow' => 'What Comes Next',
    'title' => 'Built for what comes next.',
    'body' => esa_paragraphs('Elite is built with the future in mind. Beyond daily training, student-athletes receive guidance around college preparation, scholarship pathways, NIL awareness where appropriate, and media readiness so they can step into future opportunities with clarity and confidence.'),
    'image' => $mOffice,
    'items' => [
        ['title' => 'College preparation', 'copy' => esa_paragraphs('Academic planning and athletic counseling help students prepare for college opportunities with confidence.'), 'icon' => 'college', 'icon_image' => $icon['college']],
        ['title' => 'Scholarships & NIL', 'copy' => esa_paragraphs('Students gain awareness of scholarship pathways and thoughtful NIL conversations where appropriate.'), 'icon' => 'trophy', 'icon_image' => $icon['scholarships']],
        ['title' => 'Long-term Guidance', 'copy' => esa_paragraphs('Elite helps families think beyond the next season with mentorship and future-focused pathway guidance.'), 'icon' => 'sunrise', 'icon_image' => $icon['guidance']],
    ],
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Free Summer Camps (CTA Card) -------------------------------------- */
$blocks[] = esa_block('acf/cta-card', 'group_cta_card', [
    'label' => 'Free Summer Camps',
    'title' => 'Free Summer Sports Camps at Elite Sports Academy',
    'body' => esa_paragraphs("Elite Sports Academy is hosting free summer camps for boys and girls in grades 6th through 12th. Students can train with experienced coaches, build skills, compete with other athletes, and get a firsthand feel for the Elite culture.\n\nCamps are available for basketball, football, baseball, soccer, softball, and flag football. Space is limited, so early registration is recommended."),
    'buttons' => [
        ['label' => 'Register for Free Today', 'url' => 'https://www.signupgenius.com/go/10C0B4BABAE2EA3F4C07-64094828-esasummer#/', 'new_tab' => true, 'variant' => 'primary'],
    ],
    'image' => $mCampFlyer,
    'image_side' => 'left',
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- FAQ ---------------------------------------------------------------- */
$blocks[] = esa_block('acf/faq', 'group_faq', [
    'eyebrow' => 'Family FAQs',
    'title' => 'Answers to the questions families ask first.',
    'image' => $mParent,
    'items' => [
        ['question' => 'When can we enroll?', 'answer' => '<p>Enrollment begins in January 2026. Enroll using <a href="https://heritageacademy.schoolmint.net/welcome" target="_blank" rel="noopener">this link</a> for all Heritage schools, and select Elite Sports Academy.</p>'],
        ['question' => 'Do you offer tours?', 'answer' => '<p>Yes. Families can schedule a campus tour by clicking the <a href="' . $tourUrl . '" target="_blank" rel="noopener">Schedule a Tour</a> button below.</p>'],
        ['question' => 'Do you have a mission statement?', 'answer' => esa_paragraphs("Our Mission: At Elite Sports Academy, our mission is to develop exceptional student-athletes who excel in sport, academics, and character.\n\nWe provide a rigorous balance of elite training, personalized academics, and life-skills education designed to prepare every student to thrive at the highest levels of competition and in life beyond the game.\n\nThrough world-class coaching, integrated strength and mental performance programs, and a values-driven curriculum, Elite equips athletes with the discipline, resilience, and leadership to succeed on the field, in the classroom, and in their communities.\n\nWe are committed to creating an environment where dreams are pursued with precision, passion, and purpose-empowering young men and women to not only reach the next level in their sport, but to become leaders who will inspire excellence wherever they go.")],
        ['question' => "What will the day's schedule look like?", 'answer' => '<p>Here is a potential day in the life of an Elite student. <a href="https://docs.google.com/document/d/15M1qP4EUE5fQS4AJrygK3WxkVRBJu6gx/edit?usp=sharing&ouid=116974841899665274578&rtpof=true&sd=true" target="_blank" rel="noopener">See Schedule</a>.</p>'],
        ['question' => 'Who will the coaches be?', 'answer' => '<p>Meet our current coaching staff <a href="/coaches">here</a>. Additional coaches will be announced soon.</p>'],
        ['question' => 'What electives or extracurricular activities will be available?', 'answer' => '<p>Potential extracurricular opportunities are <a href="https://drive.google.com/file/d/1AThXePiQFGI4RrO89wYNUBStF9dXfEnP/view" target="_blank" rel="noopener">listed here</a>. Clubs and additional activities will be announced as we get closer to the start of the 2026-2027 school year.</p>'],
        ['question' => 'When will the campus open?', 'answer' => '<p>The Elite campus is planned to open in late July 2026, in time for the 2026–2027 academic year.</p>'],
        ['question' => 'Will there be before or after school care?', 'answer' => '<p>We are currently exploring options to provide these services to families.</p>'],
        ['question' => 'When will jobs be posted?', 'answer' => '<p>Employment opportunities will be posted soon. Those interested in joining our team may submit a <a href="https://docs.google.com/forms/d/e/1FAIpQLSdPtPwRxB7c1M4Hm-bJZNCkBQu5f66e68cp-WiC9WBbX3TWyQ/viewform" target="_blank" rel="noopener">faculty interest form here</a>.</p>'],
        ['question' => 'What will school hours be?', 'answer' => '<p>The current plan is an 8:00 a.m. to 3:30 p.m. school day, with drop-off beginning as early as 7:30 a.m.</p>'],
        ['question' => 'Will lunch be available?', 'answer' => '<p>Students may pack lunch or purchase lunch through our vendors (once they are enrolled) using <a href="https://myhotlunchbox.com" target="_blank" rel="noopener">myhotlunchbox.com</a>.</p>'],
    ],
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Careers (CTA Card) ------------------------------------------------- */
$blocks[] = esa_block('acf/cta-card', 'group_cta_card', [
    'label' => 'Careers at Elite Sports Academy',
    'title' => 'Interested in joining our team?',
    'body' => esa_paragraphs("Elite Sports Academy is growing, and we're looking for passionate educators, coaches, and staff who want to help build a serious environment for student-athletes.\n\nIf you're committed to academic excellence, athletic development, character, and creating a positive campus culture, we'd love to hear from you."),
    'buttons' => [
        ['label' => 'View Open Positions', 'url' => 'https://heritageacaz.rec.pro.ukg.net/HER1022HACI/JobBoard/ab69e52c-dab5-46a5-9e72-7300ab45176f/?q=&o=postedDateDesc&w=&wc=&we=&wpst=&f4=a7HHlO5Q_EmplU3cs_XkwA', 'new_tab' => true, 'variant' => 'primary'],
        ['label' => 'Submit Resume for Future Opportunities', 'url' => 'https://docs.google.com/forms/d/e/1FAIpQLSdPtPwRxB7c1M4Hm-bJZNCkBQu5f66e68cp-WiC9WBbX3TWyQ/viewform', 'new_tab' => true, 'variant' => 'secondary'],
    ],
    'image' => $mTeacher,
    'image_side' => 'right',
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

/* ---- Contact ------------------------------------------------------------ */
$blocks[] = esa_block('acf/contact', 'group_contact', [
    'title' => 'Start your path at Elite Sports Academy.',
    'body' => esa_paragraphs('Tour the campus, explore the model, and see whether Elite is the right fit for your student-athlete.'),
    'address' => [
        ['text' => '10215 N 43rd Ave'],
        ['text' => 'Phoenix, AZ 85051'],
        ['text' => 'SE corner of 43rd Ave and Peoria Rd, West Phoenix'],
    ],
    'phone_label' => '480-461-4487',
    'phone_url' => 'tel:4804614487',
    'email_label' => 'info@elitesportsacademyaz.com',
    'email_url' => 'mailto:info@elitesportsacademyaz.com',
    'buttons' => [
        ['label' => 'Apply Now', 'url' => $applyUrl, 'new_tab' => true, 'variant' => 'primary'],
        ['label' => 'Schedule a Tour', 'url' => $tourUrl, 'new_tab' => true, 'variant' => 'secondary'],
    ],
    'note' => 'Media Notice: Some visuals are AI-generated, conceptual, or illustrative.',
    'padding_top' => 12,
    'padding_bottom' => 12,
]);

$content = implode("\n\n", array_filter($blocks));

// wp_insert_post / wp_update_post run wp_unslash on the content, which would
// strip the backslashes escaping quotes inside block-comment JSON (e.g. FAQ
// answers containing <a href="...">). Slash it so the JSON survives intact.
$content = wp_slash($content);

/* ---- Find or create the Home page and set it as front page ------------ */
$frontId = (int) get_option('page_on_front');
$page = $frontId ? get_post($frontId) : get_page_by_path('home');

if (! $page) {
    $page = get_page_by_title('Home');
}

if ($page) {
    $pageId = wp_update_post([
        'ID' => $page->ID,
        'post_content' => $content,
        'post_status' => 'publish',
    ], true);
} else {
    $pageId = wp_insert_post([
        'post_title' => 'Home',
        'post_name' => 'home',
        'post_status' => 'publish',
        'post_type' => 'page',
        'post_content' => $content,
    ], true);
}

if (is_wp_error($pageId)) {
    fwrite(STDERR, 'Failed to save page: ' . $pageId->get_error_message() . "\n");
    exit(1);
}

update_option('show_on_front', 'page');
update_option('page_on_front', $pageId);

printf("Seeded Home page #%d with %d blocks as the front page.\n", $pageId, count(array_filter($blocks)));
